/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package idscpayrollsystem_v01;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Time;
import java.time.LocalTime;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author lyren
 */
public class editDepartment extends javax.swing.JFrame {
    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    private Object sdf;
    /**
     * Creates new form editDepartment
     */
    public editDepartment() {
        initComponents();
        conn = dbconn.java_db();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        txt_mRate = new javax.swing.JTextField();
        txt_hpD = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        txt_dpM = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel73 = new javax.swing.JLabel();
        txt_dRate = new javax.swing.JTextField();
        jLabel75 = new javax.swing.JLabel();
        txt_hRate = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        combo_shift = new javax.swing.JComboBox();
        Date date = new Date();
        SpinnerDateModel sm =
        new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY);
        spinner_timeI = new javax.swing.JSpinner(sm);
        SpinnerDateModel sm1 =
        new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY);
        spinner_timeO = new javax.swing.JSpinner(sm1);
        jLabel76 = new javax.swing.JLabel();
        txt_searchId = new javax.swing.JTextField();
        txt_dept = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel1.setText("Edit Department");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jLabel67.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel67.setText("DEPARTMENT NAME:");

        jLabel69.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel69.setText("MONTHLY RATE:");

        txt_mRate.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        txt_mRate.setPreferredSize(new java.awt.Dimension(169, 30));
        txt_mRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mRateActionPerformed(evt);
            }
        });

        txt_hpD.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        txt_hpD.setPreferredSize(new java.awt.Dimension(169, 30));
        txt_hpD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hpDActionPerformed(evt);
            }
        });

        jLabel70.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel70.setText("HOUR (per Day):");

        jLabel68.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel68.setText("DAYS (per Month):");

        txt_dpM.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        txt_dpM.setPreferredSize(new java.awt.Dimension(169, 30));
        txt_dpM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dpMActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(160, 38, 38));
        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 50, 178));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel73.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel73.setText("DAILY RATE:");

        txt_dRate.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        txt_dRate.setPreferredSize(new java.awt.Dimension(169, 30));
        txt_dRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dRateActionPerformed(evt);
            }
        });

        jLabel75.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel75.setText("HOURLY RATE:");

        txt_hRate.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        txt_hRate.setPreferredSize(new java.awt.Dimension(169, 30));
        txt_hRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hRateActionPerformed(evt);
            }
        });

        jLabel71.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel71.setText("TIME-IN:");

        jLabel72.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel72.setText("TIME-OUT:");

        jLabel74.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel74.setText("SHIFT:");

        combo_shift.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        combo_shift.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "REGULAR", "PART-TIME" }));
        combo_shift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_shiftActionPerformed(evt);
            }
        });

        JSpinner.DateEditor de = new JSpinner.DateEditor(spinner_timeI, "HH:mm");
        spinner_timeI.setEditor(de);

        JSpinner.DateEditor de1 = new JSpinner.DateEditor(spinner_timeO, "HH:mm");
        spinner_timeO.setEditor(de1);

        jLabel76.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel76.setText("DEPARTMENT ID:");

        txt_searchId.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        txt_searchId.setPreferredSize(new java.awt.Dimension(169, 30));
        txt_searchId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchIdActionPerformed(evt);
            }
        });
        txt_searchId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchIdKeyReleased(evt);
            }
        });

        txt_dept.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        txt_dept.setPreferredSize(new java.awt.Dimension(169, 30));
        txt_dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_deptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_dpM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_hpD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinner_timeI)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinner_timeO, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_dRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_hRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_mRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combo_shift, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_searchId, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_searchId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_dpM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_hpD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_dRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_hRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinner_timeI, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(spinner_timeO, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_shift, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_mRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mRateActionPerformed

    private void txt_hpDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hpDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hpDActionPerformed

    private void txt_dpMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dpMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dpMActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
    String val = txt_dept.getText();
    String val1 = txt_mRate.getText();
    String val2 = txt_dpM.getText();
    String val3 = txt_hpD.getText();
    String val4 = txt_dRate.getText();
    String val5 = txt_hRate.getText();
    String val6 = getTimeFromSpinner(spinner_timeI);
    String val7 = getTimeFromSpinner(spinner_timeO);
    String val8 = combo_shift.getSelectedItem().toString();
    String val9 = txt_searchId.getText();

    // Using a parameterized query to prevent SQL injection
    String sql = "UPDATE department_information SET department=?, monthlyRate=?, daysperMonth=?, dailyRate=?, hoursperDay=?, hourlyRate=?, shift=?, time_in=?, time_out=? WHERE dept_id=?";
    
    pst = conn.prepareStatement(sql);
    pst.setString(1, val);
    pst.setString(2, val1);
    pst.setString(3, val2);
    pst.setString(4, val3);
    pst.setString(5, val4);
    pst.setString(6, val5);
    pst.setString(7, val8);
    pst.setString(8, val6);
    pst.setString(9, val7);
    pst.setString(10, val9);

    pst.executeUpdate();

} catch (Exception e) {
    e.printStackTrace();
    // Handle the exception (display an error message, log it, etc.)
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_dRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dRateActionPerformed

    private void txt_hRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hRateActionPerformed

    private void combo_shiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_shiftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_shiftActionPerformed

    private void txt_searchIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchIdActionPerformed

    private void txt_deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_deptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_deptActionPerformed

    private void txt_searchIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchIdKeyReleased
        // TODO add your handling code here:
        try {
            String sql ="select * from department_information where dept_id=?";

            pst=conn.prepareStatement(sql);
            pst.setString(1,txt_searchId.getText());
            rs=pst.executeQuery();
            
            if(rs.next());
            
                String add = rs.getString("dept_id");
                txt_searchId.setText(add);
            
                String add1 = rs.getString("department");
                txt_dept.setText(add1);
                
                String add2 = rs.getString("monthlyRate");
                txt_mRate.setText(add2);
                
                String add3 = rs.getString("daysperMonth");
                txt_dpM.setText(add3);
                
                String add4 = rs.getString("dailyRate");
                txt_dRate.setText(add4);
                
                String add5 = rs.getString("hoursperDay");
                txt_hpD.setText(add5);
                
                String add6 = rs.getString("hourlyRate");
                txt_hRate.setText(add6);
                
                String add7 = rs.getString("Shift");
                combo_shift.setSelectedItem(add7);
                
                Time timeIn = rs.getTime("time_in");
                Date date = new Date(timeIn.getTime());
                spinner_timeI.setModel(new SpinnerDateModel(date, null, null, java.util.Calendar.SECOND));
                spinner_timeI.setEditor(new JSpinner.DateEditor(spinner_timeI, "HH:mm"));
                
                Time timeOut = rs.getTime("time_out");
                Date date1 = new Date(timeOut.getTime());
                spinner_timeO.setModel(new SpinnerDateModel(date1, null, null, java.util.Calendar.SECOND));
                spinner_timeO.setEditor(new JSpinner.DateEditor(spinner_timeO, "HH:mm"));
            
        } catch (Exception e){
        
        } finally {

            try{

                rs.close();
                pst.close();

            }
            catch(Exception e){

            }
         }
    }//GEN-LAST:event_txt_searchIdKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editDepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editDepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editDepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editDepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editDepartment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox combo_shift;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner spinner_timeI;
    private javax.swing.JSpinner spinner_timeO;
    private javax.swing.JTextField txt_dRate;
    private javax.swing.JTextField txt_dept;
    private javax.swing.JTextField txt_dpM;
    private javax.swing.JTextField txt_hRate;
    private javax.swing.JTextField txt_hpD;
    private javax.swing.JTextField txt_mRate;
    private javax.swing.JTextField txt_searchId;
    // End of variables declaration//GEN-END:variables

    private String getTimeFromSpinner(JSpinner spinner_timeI) {
        Date date = (Date) spinner_timeI.getValue();
        Time sqlTime = new Time(date.getTime());
        return sqlTime.toString(); //To change body of generated methods, choose Tools | Templates.
    } //To change body of generated methods, choose Tools | Templates.
}
